

Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start


Logs new start

New error at 2021-06-30 14:36:44.204505:
type - <class 'psycopg2.errors.UndefinedTable'>, name - DB.py, line - 24, error - relation "forum" does not exist
LINE 1: INSERT INTO forum VALUES (290166276796448768, 1625056603.0);
                    ^



Logs new start

New error at 2021-06-30 14:37:52.786216:
type - <class 'psycopg2.errors.UndefinedTable'>, name - DB.py, line - 24, error - relation "forum" does not exist
LINE 1: INSERT INTO forum VALUES (290166276796448768, 1625056672.0);
                    ^



Logs new start

New error at 2021-06-30 14:41:04.013048:
type - <class 'psycopg2.errors.UndefinedColumn'>, name - DB.py, line - 52, error - column "userid" does not exist
LINE 1: DELETE from forum where userID = '290166276796448768';
                                ^
HINT:  Perhaps you meant to reference the column "forum.userID".


New error at 2021-06-30 14:42:40.690005:
type - <class 'psycopg2.errors.InFailedSqlTransaction'>, name - DB.py, line - 52, error - current transaction is aborted, commands ignored until end of transaction block



Logs new start


Logs new start


Logs new start


Logs new start


Logs new start

New error at 2021-06-30 18:45:26.225574:
type - <class 'psycopg2.errors.InvalidSchemaName'>, name - DB.py, line - 24, error - schema "datetime" does not exist
LINE 1: INSERT INTO forum VALUES (290166276796448768, datetime.datet...
                                                      ^



Logs new start
